name: send-trigger

on:
  # Trigger on push as well for testing purposes
  push:
    branches:
      - dev
  workflow_dispatch:
    # any additional params can be passed with the trigger POST via `inputs` param
    # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
    inputs:
      ref:
        required: true
        description: the ref to deploy

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: andycmaj/actions-isolation-product
          ref: ${{ github.event.input.ref }}

      - name: deploy
        run: |
          yarn
          node index.js
